# Site settings
title: WuZhen
email: wuzhenxiaoai@gmail.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: ""
url: "http://nandomoreira.me"

author:
  name     : 'WuZhen'
  email    : wuzhenxiaoai@gmail.com
  url      : http://nandomoreira.me
  # facebook : http://facebook.com/fernando.dev
  # twitter  : http://twitter.com/nandomoreirame

github: https://github.com/wuzhendev
disqus_shortname: "wuzhen"
# google_analytics: UA-52446115-1

paginate: 10
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
safe: false
incremental: true
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  # input: GFM
  # extensions:
    # - autolink
    # - footnotes
    # - smart
  # enable_coderay: true
  syntax_highlighter: rouge
  # coderay:
    # coderay_line_numbers:  nil

permalink : /:year/:categories/:title.html

gems: [jekyll-paginate]
