# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WuZhen
name: WuZhen
email: wuzhenxiaoai@gmail.com
location: Beijing, China
github_name: wuzhendev
github_url: https://github.com/wuzhendev
description: 吴振
favicon: favicon.png # Image must be in assets/images
slogan: 心淡然，斯为静

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://blog.wuzhendev.com
# url: http://localhost:4000

#Gems
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
permalink : /:year/:month/:title.html

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

sass:
  style: :compressed
  sass_dir: _sass

# Disqus
disque: wuzhenroid.disqus.com

# encoding
encoding: utf-8

incremental: true

# Pagination
paginate: 10
paginate_path: '/page:num'

# Comments
comments: true

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 首页

  -
    href: /footprint
    label: 足迹

  -
    href: /blog
    label: 归档

  -
    href: /about
    label: 关于

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Android, iOS, Kotlin, Swift, Scale, Go, Ruby, MySQL, Oracle, SQLite, Design Patterns, HTML5, JS, Git]

# 解析poem.json
poems:
  -
    title: 青玉案
    author: 辛弃疾
    content: 东风夜放花千树。<br>更吹落，星如雨。<br>宝马雕车香满路。<br>凤箫声动，<br>玉壶光转，<br>一夜鱼龙舞。<br><br>蛾儿雪柳黄金缕，<br>笑语盈盈暗香去。<br>众里寻他千百度，<br>蓦然回首，<br>那人却在，<br>灯火阑珊处。

  -
    title: 蝶恋花
    author: 柳永
    content: 伫倚危楼风细细，<br>望极春愁，<br>黯黯生天际。<br>草色烟光残照里，<br>无言谁会凭阑意。<br><br>拟把疏狂图一醉，<br>对酒当歌，<br>强乐还无味。<br>衣带渐宽终不悔，<br>为伊消得人憔悴。

  -
    title: 破阵子
    author: 李煜
    content: 四十年来家国，<br>三千里地山河。<br>凤阁龙楼连霄汉，<br>玉树琼枝作烟萝。<br>几曾识干戈。<br><br>一旦归为臣虏，<br>沉腰潘鬓消磨。<br>最是仓皇辞庙日，<br>教坊犹奏离别歌。<br>垂泪对宫娥。

  -
    title: 洞仙歌·泗州中秋作
    author: 晁补之
    content: 青烟幂处，<br>碧海飞金镜。<br>永夜闲阶卧桂影。<br>露凉时、零乱多少寒螀，<br>神京远，<br>惟有蓝桥路近。<br><br>水晶帘不下，<br>云母屏开，<br>冷浸佳人淡脂粉。<br>待都将许多明，<br>付与金尊，<br>投晓共、流霞倾尽。<br>更携取、胡床上南楼，<br>看玉做人间，<br>素秋千顷。

  -
    title: 临江仙
    author: 苏轼
    content: 一饮东坡醒复醉，<br>归来仿佛三更。<br>家童鼻息已雷鸣。<br>敲门都不应，<br>倚杖听江声。<br><br>长恨此身非我有，<br>何时忘却营营？<br>夜阑风静縠纹平。<br>小舟从此逝，<br>江海寄馀生。

  -
    title: 清平乐·春归何处
    author: 黄庭坚
    content: 春归何处。<br>寂寞无行路。<br>若有人知春去处。<br>唤取归来同住。<br><br>春无踪迹谁知。<br>除非问取黄鹂。<br>百啭无人能解，<br>因风飞过蔷薇。

  -
    title: 相见欢
    author: 李煜
    content: 林花谢了春红，<br>太匆匆，<br>无奈朝来寒雨晚来风。<br><br>胭脂泪，<br>相留醉，<br>几时重。<br>自是人生长恨水长东。

  -
    title: 定风波
    author: 苏轼
    content: 莫听穿林打叶声，<br>何妨吟啸且徐行。<br>竹杖芒鞋轻胜马，<br>谁怕？<br>一蓑烟雨任平生。<br><br>料峭春风吹酒醒，<br>微冷，<br>山头斜照却相迎。<br>回首向来萧瑟处，<br>归去，<br>也无风雨也无晴。

  -
    title: 蝶恋花·早行
    author: 周邦彦
    content: 月皎惊乌栖不定，<br>更漏将残，<br>辘轳牵金井。<br>唤起两眸清炯炯。<br>泪花落枕红绵冷。<br><br>执手霜风吹鬓影。<br>去意徊徨，<br>别语愁难听。<br>楼上阑干横斗柄，<br>露寒人远鸡相应。

  -
    title: 憾庭秋
    author: 晏殊
    content: 别来音信千里，<br>恨此情难寄。<br>碧纱秋月，<br>梧桐夜雨，<br>几回无寐。<br><br>楼高目断，<br>天遥云暗，<br>只堪憔悴。<br>念兰堂红烛，<br>心长焰短，<br>向人垂泪。

  -
    title: 夜游宫·记梦寄师伯浑
    author: 陆游
    content: 雪晓清笳乱起，<br>梦游处，<br>不知何地。<br>铁骑无声望似水。<br>想关河：雁门西，<br>青海际。<br><br>睡觉寒灯里，<br>漏声断，<br>月斜窗纸。<br>自许封侯在万里。<br>有谁知，<br>鬓虽残，<br>心未死！

  -
    title: 浪淘沙令
    author: 李煜
    content: 帘外雨潺潺，<br>春意阑珊。<br>罗衾不耐五更寒。<br>梦里不知身是客，<br>一晌贪欢。<br><br>独自莫凭栏，<br>无限江山，<br>别时容易见时难。<br>流水落花春去也，<br>天上人间。

  -
    title: 鹧鸪天
    author: 晏几道
    content: 醉柏春衫惜旧香，<br>天将离恨恼疏狂。<br>年年陌上生秋草，<br>日日楼中到夕阳。<br><br>云渺渺，<br>水茫茫，<br>征人归路许多长。<br>相思本是无凭语，<br>莫向花笺费泪行。

  -
    title: 玉楼春
    author: 辛弃疾
    content: 江头一带斜阳树。<br>总是六朝人住处。<br>悠悠兴废不关心，<br>惟有沙洲双白鹭。<br><br>仙人矶下多风雨。<br>好卸征帆留不住。<br>直须抖擞尽尘埃，<br>却趁新凉秋水去。

  -
    title: 长相思
    author: 纳兰容若
    content: 山一程，<br>水一程，<br>身向榆关那畔行，<br>夜深千帐灯。<br><br>风一更，<br>雪一更，<br>聒碎乡心梦不成，<br>故园无此声。

  -
    title: 忆帝京
    author: 柳永
    content: 薄衾小枕凉天气，<br>乍觉别离滋味。<br>辗转数寒更，<br>起了还重睡。<br>毕竟不成眠，<br>一夜长如岁。<br><br>也拟待，<br>却回征辔。<br>又争奈，<br>已成行计。<br>万种思量，<br>多方开解，<br>只恁寂寞厌厌地。<br>系我一生心，<br>负你千行泪。
